#############################################################
# DMA Makefile
#############################################################
.DEFAULT_GOAL=all

# Add your applications here
BINS=$(notdir $(wildcard cmd/*))

# Include versions generated by BAKE
#$(foreach var,"0.1",$(eval $(var)))
VERSION=v0.0.1
VERSION_NO_RC=v0.0.1
DEB_VERSION=0.0.1

$(info $$VERSION = $(VERSION))

# Disable CGO for completely static binaries.
export CGO_ENABLED=0

export VERSION
export DEB_VERSION

all: $(BINS)

$(BINS): generate
	go build -ldflags="-s -w" ./cmd/$@

generate:
	go generate ./...

test: generate
	go test ./...

deb: $(BINS)
	$(MAKE) -C package

clean:
	$(MAKE) -C package clean

realclean: clean

.PHONY : all generate deb clean realclean
.PHONY : $(BINS)
