#!/bin/sh
set -e

echo "Entering postinst with argument '$1'" >&1
case "$1" in
configure)
  echo "configuring services" >&2
  systemctl daemon-reload
  systemctl enable --now gtools.service
  systemctl restart gtools
  ;;

abort-upgrade | abort-remove | abort-deconfigure) ;;

*)
  echo "postinst called with unknown argument '$1'" >&2
  exit 1
  ;;
esac

exit 0
